# This is a config for E2B sandbox template.
# You can use template ID (lxtp1mbmuj98ppp9dodw) or template name (vibe-nextjs-test-by-olksnd-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-by-olksnd-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-by-olksnd-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-by-olksnd-2')

team_id = "6c9ed943-97b0-4593-94f3-4b05b334698d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-by-olksnd-2"
template_id = "lxtp1mbmuj98ppp9dodw"
